version: '3'

networks:
  app:
    driver: bridge

services:
  app:
    image: afladev/php-nginx:8.2
    environment:
        - WEB_DOCUMENT_ROOT=/app/public
    working_dir: '/app'
    volumes:
      - '.:/app'
    networks:
        - app
    ports:
      - ${APP_PORT:-80}:80

  node:
    image: node:18
    working_dir: '/app'
    volumes:
      - '.:/app'
    networks:
      - app
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    command: ["/bin/bash", "-c", "tail -f /dev/null"]

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'
    networks:
      - app

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - app
